"""Initial migration.

Revision ID: 1040e487234b
Revises: 5c56618c1d5a
Create Date: 2025-03-10 11:44:20.548598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1040e487234b'
down_revision = '5c56618c1d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imsi', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('imei', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('imei')
        batch_op.drop_column('imsi')

    # ### end Alembic commands ###
