"""Initial migration.

Revision ID: 220ff39116a3
Revises: 
Create Date: 2024-06-29 15:58:28.358921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220ff39116a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('readkey', sa.String(length=100), nullable=True),
    sa.Column('writekey', sa.String(length=100), nullable=True),
    sa.Column('file_download_state', sa.String(length=100), nullable=True),
    sa.Column('field1', sa.String(length=100), nullable=True),
    sa.Column('field2', sa.String(length=100), nullable=True),
    sa.Column('field3', sa.String(length=100), nullable=True),
    sa.Column('field4', sa.String(length=100), nullable=True),
    sa.Column('field5', sa.String(length=100), nullable=True),
    sa.Column('field6', sa.String(length=100), nullable=True),
    sa.Column('field7', sa.String(length=100), nullable=True),
    sa.Column('field8', sa.String(length=100), nullable=True),
    sa.Column('field9', sa.String(length=100), nullable=True),
    sa.Column('field10', sa.String(length=100), nullable=True),
    sa.Column('field11', sa.String(length=100), nullable=True),
    sa.Column('field12', sa.String(length=100), nullable=True),
    sa.Column('field13', sa.String(length=100), nullable=True),
    sa.Column('field14', sa.String(length=100), nullable=True),
    sa.Column('field15', sa.String(length=100), nullable=True),
    sa.Column('field16', sa.String(length=100), nullable=True),
    sa.Column('field17', sa.String(length=100), nullable=True),
    sa.Column('field18', sa.String(length=100), nullable=True),
    sa.Column('field19', sa.String(length=100), nullable=True),
    sa.Column('field20', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadatavalues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deviceID', sa.Integer(), nullable=True),
    sa.Column('field1', sa.String(length=100), nullable=True),
    sa.Column('field2', sa.String(length=100), nullable=True),
    sa.Column('field3', sa.String(length=100), nullable=True),
    sa.Column('field4', sa.String(length=100), nullable=True),
    sa.Column('field5', sa.String(length=100), nullable=True),
    sa.Column('field6', sa.String(length=100), nullable=True),
    sa.Column('field7', sa.String(length=100), nullable=True),
    sa.Column('field8', sa.String(length=100), nullable=True),
    sa.Column('field9', sa.String(length=100), nullable=True),
    sa.Column('field10', sa.String(length=100), nullable=True),
    sa.Column('field11', sa.String(length=100), nullable=True),
    sa.Column('field12', sa.String(length=100), nullable=True),
    sa.Column('field13', sa.String(length=100), nullable=True),
    sa.Column('field14', sa.String(length=100), nullable=True),
    sa.Column('field15', sa.String(length=100), nullable=True),
    sa.Column('field16', sa.String(length=100), nullable=True),
    sa.Column('field17', sa.String(length=100), nullable=True),
    sa.Column('field18', sa.String(length=100), nullable=True),
    sa.Column('field19', sa.String(length=100), nullable=True),
    sa.Column('field20', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['deviceID'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadatavalues')
    op.drop_table('devices')
    # ### end Alembic commands ###
