"""more updates

Revision ID: 2ccce4ee6653
Revises: 1f99cad81d72
Create Date: 2024-08-14 13:54:51.015470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ccce4ee6653'
down_revision = '1f99cad81d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('field21')

    with op.batch_alter_table('metadatavalues', schema=None) as batch_op:
        batch_op.drop_column('field21')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metadatavalues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field21', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field21', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
