"""Initial migration.

Revision ID: 2ee46b9db5d3
Revises: a0963467a88a
Create Date: 2025-04-05 19:21:09.389892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee46b9db5d3'
down_revision = 'a0963467a88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('networkID', sa.String(length=100), nullable=True))
        batch_op.drop_column('imei')
        batch_op.drop_column('imsi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imsi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('imei', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('networkID')

    # ### end Alembic commands ###
