"""Initial migration.

Revision ID: 375d8b43f7da
Revises: d4c4502e2a2b
Create Date: 2025-04-05 18:32:43.876185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375d8b43f7da'
down_revision = 'd4c4502e2a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configvalues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deviceID', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('configs', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['deviceID'], ['devices.deviceID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('firmware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changes', sa.JSON(), nullable=True))
        batch_op.drop_column('change6')
        batch_op.drop_column('change8')
        batch_op.drop_column('change4')
        batch_op.drop_column('change1')
        batch_op.drop_column('change10')
        batch_op.drop_column('change7')
        batch_op.drop_column('change3')
        batch_op.drop_column('change9')
        batch_op.drop_column('change5')
        batch_op.drop_column('change2')

    with op.batch_alter_table('metadatavalues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fields', sa.JSON(), nullable=True))
        batch_op.drop_column('field18')
        batch_op.drop_column('field20')
        batch_op.drop_column('field1')
        batch_op.drop_column('field11')
        batch_op.drop_column('field2')
        batch_op.drop_column('field4')
        batch_op.drop_column('field7')
        batch_op.drop_column('field19')
        batch_op.drop_column('field12')
        batch_op.drop_column('field14')
        batch_op.drop_column('field3')
        batch_op.drop_column('field10')
        batch_op.drop_column('field13')
        batch_op.drop_column('field9')
        batch_op.drop_column('field8')
        batch_op.drop_column('field5')
        batch_op.drop_column('field15')
        batch_op.drop_column('field6')
        batch_op.drop_column('field16')
        batch_op.drop_column('field17')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fields', sa.JSON(), nullable=True))
        batch_op.drop_column('field2')
        batch_op.drop_column('field8_mark')
        batch_op.drop_column('field10_mark')
        batch_op.drop_column('field7')
        batch_op.drop_column('field19')
        batch_op.drop_column('field12_mark')
        batch_op.drop_column('field14')
        batch_op.drop_column('field6_mark')
        batch_op.drop_column('field15_mark')
        batch_op.drop_column('field2_mark')
        batch_op.drop_column('field3')
        batch_op.drop_column('field4_mark')
        batch_op.drop_column('field11_mark')
        batch_op.drop_column('field5_mark')
        batch_op.drop_column('field13')
        batch_op.drop_column('field9_mark')
        batch_op.drop_column('field3_mark')
        batch_op.drop_column('field5')
        batch_op.drop_column('field15')
        batch_op.drop_column('field14_mark')
        batch_op.drop_column('field17')
        batch_op.drop_column('field18')
        batch_op.drop_column('field20')
        batch_op.drop_column('field18_mark')
        batch_op.drop_column('field1')
        batch_op.drop_column('field11')
        batch_op.drop_column('field17_mark')
        batch_op.drop_column('field4')
        batch_op.drop_column('field16_mark')
        batch_op.drop_column('field20_mark')
        batch_op.drop_column('field12')
        batch_op.drop_column('field19_mark')
        batch_op.drop_column('field10')
        batch_op.drop_column('field9')
        batch_op.drop_column('field8')
        batch_op.drop_column('field13_mark')
        batch_op.drop_column('field6')
        batch_op.drop_column('field16')
        batch_op.drop_column('field7_mark')
        batch_op.drop_column('field1_mark')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field1_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field7_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field16', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field6', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field13_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field8', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field9', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field10', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field19_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field12', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field20_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field16_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field4', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field17_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field11', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field1', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field18_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field20', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field18', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field17', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field14_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field15', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field5', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field3_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field9_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field13', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field5_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field11_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field4_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field3', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field2_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field15_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field6_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field14', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field12_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field19', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field7', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field10_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field8_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field2', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('fields')

    with op.batch_alter_table('metadatavalues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field17', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field16', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field6', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field15', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field5', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field8', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field9', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field13', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field10', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field3', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field14', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field12', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field19', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field7', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field4', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field2', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field11', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field1', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field20', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field18', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('fields')

    with op.batch_alter_table('firmware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change2', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('change5', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('change9', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('change3', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('change7', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('change10', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('change1', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('change4', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('change8', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('change6', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('changes')

    op.drop_table('configvalues')
    # ### end Alembic commands ###
