"""changes to the firmware table

Revision ID: 39f6d24a9018
Revises: 9d3bb6d8060f
Create Date: 2024-10-07 20:11:55.350601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f6d24a9018'
down_revision = '9d3bb6d8060f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('targetFirmwareVersion', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'firmware', ['targetFirmwareVersion'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('targetFirmwareVersion')

    # ### end Alembic commands ###
