"""Initial migration.

Revision ID: 3b2c25bc4309
Revises: fbe27bfd669b
Create Date: 2024-07-11 14:33:10.852196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2c25bc4309'
down_revision = 'fbe27bfd669b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firmware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))
        batch_op.drop_column('descrption')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firmware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descrption', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
