"""more updates

Revision ID: 4016eae28258
Revises: 4e73ad089fb0
Create Date: 2024-08-14 17:47:10.004915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4016eae28258'
down_revision = '4e73ad089fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('file_download_state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_download_state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
