"""more updates

Revision ID: 4e73ad089fb0
Revises: 396104866df7
Create Date: 2024-08-14 17:45:03.463213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e73ad089fb0'
down_revision = '396104866df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint('devices_firmwareVersion_fkey', type_='foreignkey')
        batch_op.drop_column('firmwareVersion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firmwareVersion', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('devices_firmwareVersion_fkey', 'firmware', ['firmwareVersion'], ['id'])

    # ### end Alembic commands ###
