"""mark added

Revision ID: 59764d25947b
Revises: 39f6d24a9018
Create Date: 2025-02-07 15:41:23.618449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59764d25947b'
down_revision = '39f6d24a9018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field1_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field2_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field3_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field4_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field5_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field6_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field7_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field8_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field9_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field10_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field11_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field12_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field13_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field14_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field15_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field16_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field17_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field18_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field19_mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('field20_mark', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('field20_mark')
        batch_op.drop_column('field19_mark')
        batch_op.drop_column('field18_mark')
        batch_op.drop_column('field17_mark')
        batch_op.drop_column('field16_mark')
        batch_op.drop_column('field15_mark')
        batch_op.drop_column('field14_mark')
        batch_op.drop_column('field13_mark')
        batch_op.drop_column('field12_mark')
        batch_op.drop_column('field11_mark')
        batch_op.drop_column('field10_mark')
        batch_op.drop_column('field9_mark')
        batch_op.drop_column('field8_mark')
        batch_op.drop_column('field7_mark')
        batch_op.drop_column('field6_mark')
        batch_op.drop_column('field5_mark')
        batch_op.drop_column('field4_mark')
        batch_op.drop_column('field3_mark')
        batch_op.drop_column('field2_mark')
        batch_op.drop_column('field1_mark')

    # ### end Alembic commands ###
