"""Initial migration.

Revision ID: 598dfb583552
Revises: 2ee46b9db5d3
Create Date: 2025-04-09 13:16:40.641987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598dfb583552'
down_revision = '2ee46b9db5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firmware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firmware_type', sa.Enum('stable', 'beta', 'deprecated', 'legacy', name='firmware_type_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firmware', schema=None) as batch_op:
        batch_op.drop_column('firmware_type')

    # ### end Alembic commands ###
