"""more updates

Revision ID: 59a472e8ee88
Revises: 4016eae28258
Create Date: 2024-08-21 17:05:29.529239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a472e8ee88'
down_revision = '4016eae28258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currentFirmwareVersion', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updateFirmwareVersion', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('file_download_state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.create_foreign_key(None, 'firmware', ['currentFirmwareVersion'], ['id'])
        batch_op.create_foreign_key(None, 'firmware', ['updateFirmwareVersion'], ['id'])

    with op.batch_alter_table('firmware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('metadatavalues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metadatavalues', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('firmware', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('file_download_state')
        batch_op.drop_column('updateFirmwareVersion')
        batch_op.drop_column('currentFirmwareVersion')

    # ### end Alembic commands ###
