"""Initial migration.

Revision ID: 5c56618c1d5a
Revises: d0e2f07ee354
Create Date: 2025-03-05 15:20:33.294063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c56618c1d5a'
down_revision = 'd0e2f07ee354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devicefiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deviceID', sa.Integer(), nullable=True),
    sa.Column('file', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deviceID'], ['devices.deviceID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devicefiles')
    # ### end Alembic commands ###
