"""more updates

Revision ID: 76c51a867c08
Revises: 59a472e8ee88
Create Date: 2024-09-03 10:50:31.706420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c51a867c08'
down_revision = '59a472e8ee88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previousFirmwareVersion', sa.Integer(), nullable=True))
        batch_op.drop_constraint('devices_updateFirmwareVersion_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'firmware', ['previousFirmwareVersion'], ['id'])
        batch_op.drop_column('updateFirmwareVersion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updateFirmwareVersion', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('devices_updateFirmwareVersion_fkey', 'firmware', ['updateFirmwareVersion'], ['id'])
        batch_op.drop_column('previousFirmwareVersion')

    # ### end Alembic commands ###
