"""more updates

Revision ID: 7eea66f24863
Revises: 3b2c25bc4309
Create Date: 2024-08-14 13:01:28.455876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eea66f24863'
down_revision = '3b2c25bc4309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metadatavalues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field21', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metadatavalues', schema=None) as batch_op:
        batch_op.drop_column('field21')

    # ### end Alembic commands ###
