"""more updates

Revision ID: 804261de2f1e
Revises: 76c51a867c08
Create Date: 2024-09-03 12:00:06.427499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804261de2f1e'
down_revision = '76c51a867c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fileDownloadState', sa.Boolean(), nullable=True))
        batch_op.drop_column('file_download_state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_download_state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('fileDownloadState')

    # ### end Alembic commands ###
