"""changes to the firmware table

Revision ID: 9d3bb6d8060f
Revises: 8361ec680f2b
Create Date: 2024-10-02 18:12:43.891584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3bb6d8060f'
down_revision = '8361ec680f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firmware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documentation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('documentationLink', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change4', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change5', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change6', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change7', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change8', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change9', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change10', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firmware', schema=None) as batch_op:
        batch_op.drop_column('change10')
        batch_op.drop_column('change9')
        batch_op.drop_column('change8')
        batch_op.drop_column('change7')
        batch_op.drop_column('change6')
        batch_op.drop_column('change5')
        batch_op.drop_column('change4')
        batch_op.drop_column('change3')
        batch_op.drop_column('change2')
        batch_op.drop_column('change1')
        batch_op.drop_column('documentationLink')
        batch_op.drop_column('documentation')

    # ### end Alembic commands ###
