"""Initial migration.

Revision ID: a0963467a88a
Revises: 375d8b43f7da
Create Date: 2025-04-05 18:39:46.068972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0963467a88a'
down_revision = '375d8b43f7da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configvalues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config4', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config5', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config6', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config7', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config8', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config9', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config10', sa.String(length=100), nullable=True))
        batch_op.drop_column('configs')

    with op.batch_alter_table('firmware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change4', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change5', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change6', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change7', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change8', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change9', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('change10', sa.String(length=100), nullable=True))
        batch_op.drop_column('changes')

    with op.batch_alter_table('metadatavalues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field4', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field5', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field6', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field7', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field8', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field9', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field10', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field11', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field12', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field13', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field14', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field15', sa.String(length=100), nullable=True))
        batch_op.drop_column('fields')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field4', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field5', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field6', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field7', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field8', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field9', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field10', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field11', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field12', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field13', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field14', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field15', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config4', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config5', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config6', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config7', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config8', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config9', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('config10', sa.String(length=100), nullable=True))
        batch_op.drop_column('fields')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('config10')
        batch_op.drop_column('config9')
        batch_op.drop_column('config8')
        batch_op.drop_column('config7')
        batch_op.drop_column('config6')
        batch_op.drop_column('config5')
        batch_op.drop_column('config4')
        batch_op.drop_column('config3')
        batch_op.drop_column('config2')
        batch_op.drop_column('config1')
        batch_op.drop_column('field15')
        batch_op.drop_column('field14')
        batch_op.drop_column('field13')
        batch_op.drop_column('field12')
        batch_op.drop_column('field11')
        batch_op.drop_column('field10')
        batch_op.drop_column('field9')
        batch_op.drop_column('field8')
        batch_op.drop_column('field7')
        batch_op.drop_column('field6')
        batch_op.drop_column('field5')
        batch_op.drop_column('field4')
        batch_op.drop_column('field3')
        batch_op.drop_column('field2')
        batch_op.drop_column('field1')

    with op.batch_alter_table('metadatavalues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('field15')
        batch_op.drop_column('field14')
        batch_op.drop_column('field13')
        batch_op.drop_column('field12')
        batch_op.drop_column('field11')
        batch_op.drop_column('field10')
        batch_op.drop_column('field9')
        batch_op.drop_column('field8')
        batch_op.drop_column('field7')
        batch_op.drop_column('field6')
        batch_op.drop_column('field5')
        batch_op.drop_column('field4')
        batch_op.drop_column('field3')
        batch_op.drop_column('field2')
        batch_op.drop_column('field1')

    with op.batch_alter_table('firmware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('change10')
        batch_op.drop_column('change9')
        batch_op.drop_column('change8')
        batch_op.drop_column('change7')
        batch_op.drop_column('change6')
        batch_op.drop_column('change5')
        batch_op.drop_column('change4')
        batch_op.drop_column('change3')
        batch_op.drop_column('change2')
        batch_op.drop_column('change1')

    with op.batch_alter_table('configvalues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('configs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('config10')
        batch_op.drop_column('config9')
        batch_op.drop_column('config8')
        batch_op.drop_column('config7')
        batch_op.drop_column('config6')
        batch_op.drop_column('config5')
        batch_op.drop_column('config4')
        batch_op.drop_column('config3')
        batch_op.drop_column('config2')
        batch_op.drop_column('config1')

    # ### end Alembic commands ###
