"""Initial migration.

Revision ID: d0e2f07ee354
Revises: e79e49c54e01
Create Date: 2025-03-05 10:47:00.055247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e2f07ee354'
down_revision = 'e79e49c54e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firmware', schema=None) as batch_op:
        batch_op.alter_column('firmware_string_hex',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firmware', schema=None) as batch_op:
        batch_op.alter_column('firmware_string_hex',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
