"""Initial migration.

Revision ID: d3dc91e55206
Revises: 
Create Date: 2025-04-15 14:52:27.199467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3dc91e55206'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmware',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firmwareVersion', sa.String(length=100), nullable=True),
    sa.Column('firmware_string', sa.String(length=100), nullable=False),
    sa.Column('firmware_string_hex', sa.String(length=100), nullable=True),
    sa.Column('firmware_string_bootloader', sa.String(length=100), nullable=True),
    sa.Column('firmware_type', sa.Enum('stable', 'beta', 'deprecated', 'legacy', name='firmware_type_enum'), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('change1', sa.String(length=100), nullable=True),
    sa.Column('change2', sa.String(length=100), nullable=True),
    sa.Column('change3', sa.String(length=100), nullable=True),
    sa.Column('change4', sa.String(length=100), nullable=True),
    sa.Column('change5', sa.String(length=100), nullable=True),
    sa.Column('change6', sa.String(length=100), nullable=True),
    sa.Column('change7', sa.String(length=100), nullable=True),
    sa.Column('change8', sa.String(length=100), nullable=True),
    sa.Column('change9', sa.String(length=100), nullable=True),
    sa.Column('change10', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firmwareVersion')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('field1', sa.String(length=100), nullable=True),
    sa.Column('field2', sa.String(length=100), nullable=True),
    sa.Column('field3', sa.String(length=100), nullable=True),
    sa.Column('field4', sa.String(length=100), nullable=True),
    sa.Column('field5', sa.String(length=100), nullable=True),
    sa.Column('field6', sa.String(length=100), nullable=True),
    sa.Column('field7', sa.String(length=100), nullable=True),
    sa.Column('field8', sa.String(length=100), nullable=True),
    sa.Column('field9', sa.String(length=100), nullable=True),
    sa.Column('field10', sa.String(length=100), nullable=True),
    sa.Column('field11', sa.String(length=100), nullable=True),
    sa.Column('field12', sa.String(length=100), nullable=True),
    sa.Column('field13', sa.String(length=100), nullable=True),
    sa.Column('field14', sa.String(length=100), nullable=True),
    sa.Column('field15', sa.String(length=100), nullable=True),
    sa.Column('metadata1', sa.String(length=100), nullable=True),
    sa.Column('metadata2', sa.String(length=100), nullable=True),
    sa.Column('metadata3', sa.String(length=100), nullable=True),
    sa.Column('metadata4', sa.String(length=100), nullable=True),
    sa.Column('metadata5', sa.String(length=100), nullable=True),
    sa.Column('metadata6', sa.String(length=100), nullable=True),
    sa.Column('metadata7', sa.String(length=100), nullable=True),
    sa.Column('metadata8', sa.String(length=100), nullable=True),
    sa.Column('metadata9', sa.String(length=100), nullable=True),
    sa.Column('metadata10', sa.String(length=100), nullable=True),
    sa.Column('metadata11', sa.String(length=100), nullable=True),
    sa.Column('metadata12', sa.String(length=100), nullable=True),
    sa.Column('metadata13', sa.String(length=100), nullable=True),
    sa.Column('metadata14', sa.String(length=100), nullable=True),
    sa.Column('metadata15', sa.String(length=100), nullable=True),
    sa.Column('config1', sa.String(length=100), nullable=True),
    sa.Column('config2', sa.String(length=100), nullable=True),
    sa.Column('config3', sa.String(length=100), nullable=True),
    sa.Column('config4', sa.String(length=100), nullable=True),
    sa.Column('config5', sa.String(length=100), nullable=True),
    sa.Column('config6', sa.String(length=100), nullable=True),
    sa.Column('config7', sa.String(length=100), nullable=True),
    sa.Column('config8', sa.String(length=100), nullable=True),
    sa.Column('config9', sa.String(length=100), nullable=True),
    sa.Column('config10', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('readkey', sa.String(length=100), nullable=True),
    sa.Column('deviceID', sa.Integer(), nullable=True),
    sa.Column('writekey', sa.String(length=100), nullable=True),
    sa.Column('networkID', sa.String(length=100), nullable=True),
    sa.Column('currentFirmwareVersion', sa.Integer(), nullable=True),
    sa.Column('previousFirmwareVersion', sa.Integer(), nullable=True),
    sa.Column('targetFirmwareVersion', sa.Integer(), nullable=True),
    sa.Column('fileDownloadState', sa.Boolean(), nullable=True),
    sa.Column('profile', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['currentFirmwareVersion'], ['firmware.id'], ),
    sa.ForeignKeyConstraint(['previousFirmwareVersion'], ['firmware.id'], ),
    sa.ForeignKeyConstraint(['profile'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['targetFirmwareVersion'], ['firmware.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deviceID'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('readkey'),
    sa.UniqueConstraint('writekey')
    )
    op.create_table('configvalues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deviceID', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('config1', sa.String(length=100), nullable=True),
    sa.Column('config2', sa.String(length=100), nullable=True),
    sa.Column('config3', sa.String(length=100), nullable=True),
    sa.Column('config4', sa.String(length=100), nullable=True),
    sa.Column('config5', sa.String(length=100), nullable=True),
    sa.Column('config6', sa.String(length=100), nullable=True),
    sa.Column('config7', sa.String(length=100), nullable=True),
    sa.Column('config8', sa.String(length=100), nullable=True),
    sa.Column('config9', sa.String(length=100), nullable=True),
    sa.Column('config10', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['deviceID'], ['devices.deviceID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devicedata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entryID', sa.Integer(), nullable=True),
    sa.Column('deviceID', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('field1', sa.String(length=100), nullable=True),
    sa.Column('field2', sa.String(length=100), nullable=True),
    sa.Column('field3', sa.String(length=100), nullable=True),
    sa.Column('field4', sa.String(length=100), nullable=True),
    sa.Column('field5', sa.String(length=100), nullable=True),
    sa.Column('field6', sa.String(length=100), nullable=True),
    sa.Column('field7', sa.String(length=100), nullable=True),
    sa.Column('field8', sa.String(length=100), nullable=True),
    sa.Column('field9', sa.String(length=100), nullable=True),
    sa.Column('field10', sa.String(length=100), nullable=True),
    sa.Column('field11', sa.String(length=100), nullable=True),
    sa.Column('field12', sa.String(length=100), nullable=True),
    sa.Column('field13', sa.String(length=100), nullable=True),
    sa.Column('field14', sa.String(length=100), nullable=True),
    sa.Column('field15', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['deviceID'], ['devices.deviceID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deviceID', 'entryID', name='unique_device_entry')
    )
    op.create_table('devicefiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deviceID', sa.Integer(), nullable=True),
    sa.Column('file', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deviceID'], ['devices.deviceID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadatavalues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deviceID', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('metadata1', sa.String(length=100), nullable=True),
    sa.Column('metadata2', sa.String(length=100), nullable=True),
    sa.Column('metadata3', sa.String(length=100), nullable=True),
    sa.Column('metadata4', sa.String(length=100), nullable=True),
    sa.Column('metadata5', sa.String(length=100), nullable=True),
    sa.Column('metadata6', sa.String(length=100), nullable=True),
    sa.Column('metadata7', sa.String(length=100), nullable=True),
    sa.Column('metadata8', sa.String(length=100), nullable=True),
    sa.Column('metadata9', sa.String(length=100), nullable=True),
    sa.Column('metadata10', sa.String(length=100), nullable=True),
    sa.Column('metadata11', sa.String(length=100), nullable=True),
    sa.Column('metadata12', sa.String(length=100), nullable=True),
    sa.Column('metadata13', sa.String(length=100), nullable=True),
    sa.Column('metadata14', sa.String(length=100), nullable=True),
    sa.Column('metadata15', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['deviceID'], ['devices.deviceID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadatavalues')
    op.drop_table('devicefiles')
    op.drop_table('devicedata')
    op.drop_table('configvalues')
    op.drop_table('devices')
    op.drop_table('profiles')
    op.drop_table('firmware')
    # ### end Alembic commands ###
