"""Initial migration.

Revision ID: d4c4502e2a2b
Revises: 1040e487234b
Create Date: 2025-03-10 12:07:50.648115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c4502e2a2b'
down_revision = '1040e487234b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('field1', sa.String(length=100), nullable=True),
    sa.Column('field1_mark', sa.Boolean(), nullable=True),
    sa.Column('field2', sa.String(length=100), nullable=True),
    sa.Column('field2_mark', sa.Boolean(), nullable=True),
    sa.Column('field3', sa.String(length=100), nullable=True),
    sa.Column('field3_mark', sa.Boolean(), nullable=True),
    sa.Column('field4', sa.String(length=100), nullable=True),
    sa.Column('field4_mark', sa.Boolean(), nullable=True),
    sa.Column('field5', sa.String(length=100), nullable=True),
    sa.Column('field5_mark', sa.Boolean(), nullable=True),
    sa.Column('field6', sa.String(length=100), nullable=True),
    sa.Column('field6_mark', sa.Boolean(), nullable=True),
    sa.Column('field7', sa.String(length=100), nullable=True),
    sa.Column('field7_mark', sa.Boolean(), nullable=True),
    sa.Column('field8', sa.String(length=100), nullable=True),
    sa.Column('field8_mark', sa.Boolean(), nullable=True),
    sa.Column('field9', sa.String(length=100), nullable=True),
    sa.Column('field9_mark', sa.Boolean(), nullable=True),
    sa.Column('field10', sa.String(length=100), nullable=True),
    sa.Column('field10_mark', sa.Boolean(), nullable=True),
    sa.Column('field11', sa.String(length=100), nullable=True),
    sa.Column('field11_mark', sa.Boolean(), nullable=True),
    sa.Column('field12', sa.String(length=100), nullable=True),
    sa.Column('field12_mark', sa.Boolean(), nullable=True),
    sa.Column('field13', sa.String(length=100), nullable=True),
    sa.Column('field13_mark', sa.Boolean(), nullable=True),
    sa.Column('field14', sa.String(length=100), nullable=True),
    sa.Column('field14_mark', sa.Boolean(), nullable=True),
    sa.Column('field15', sa.String(length=100), nullable=True),
    sa.Column('field15_mark', sa.Boolean(), nullable=True),
    sa.Column('field16', sa.String(length=100), nullable=True),
    sa.Column('field16_mark', sa.Boolean(), nullable=True),
    sa.Column('field17', sa.String(length=100), nullable=True),
    sa.Column('field17_mark', sa.Boolean(), nullable=True),
    sa.Column('field18', sa.String(length=100), nullable=True),
    sa.Column('field18_mark', sa.Boolean(), nullable=True),
    sa.Column('field19', sa.String(length=100), nullable=True),
    sa.Column('field19_mark', sa.Boolean(), nullable=True),
    sa.Column('field20', sa.String(length=100), nullable=True),
    sa.Column('field20_mark', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'profiles', ['profile'], ['id'])
        batch_op.drop_column('field20')
        batch_op.drop_column('field8_mark')
        batch_op.drop_column('field4')
        batch_op.drop_column('field20_mark')
        batch_op.drop_column('field14_mark')
        batch_op.drop_column('field8')
        batch_op.drop_column('field11')
        batch_op.drop_column('field15_mark')
        batch_op.drop_column('field16_mark')
        batch_op.drop_column('field12')
        batch_op.drop_column('field19_mark')
        batch_op.drop_column('field18')
        batch_op.drop_column('field19')
        batch_op.drop_column('field17_mark')
        batch_op.drop_column('field5_mark')
        batch_op.drop_column('field3')
        batch_op.drop_column('field2_mark')
        batch_op.drop_column('field14')
        batch_op.drop_column('field9_mark')
        batch_op.drop_column('field13_mark')
        batch_op.drop_column('field2')
        batch_op.drop_column('field6_mark')
        batch_op.drop_column('field9')
        batch_op.drop_column('field3_mark')
        batch_op.drop_column('field4_mark')
        batch_op.drop_column('field18_mark')
        batch_op.drop_column('field12_mark')
        batch_op.drop_column('field1_mark')
        batch_op.drop_column('field10_mark')
        batch_op.drop_column('field5')
        batch_op.drop_column('field16')
        batch_op.drop_column('field15')
        batch_op.drop_column('field17')
        batch_op.drop_column('field10')
        batch_op.drop_column('field7')
        batch_op.drop_column('field1')
        batch_op.drop_column('field7_mark')
        batch_op.drop_column('field6')
        batch_op.drop_column('field11_mark')
        batch_op.drop_column('field13')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field13', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field11_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field6', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field7_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field1', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field7', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field10', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field17', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field15', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field16', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field5', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field10_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field1_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field12_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field18_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field4_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field3_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field9', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field6_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field2', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field13_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field9_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field14', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field2_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field3', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field5_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field17_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field19', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field18', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field19_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field12', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field16_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field15_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field11', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field8', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field14_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field20_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field4', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field8_mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('field20', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('profile')

    op.drop_table('profiles')
    # ### end Alembic commands ###
