"""Initial migration.

Revision ID: da811f152354
Revises: 598dfb583552
Create Date: 2025-04-11 11:36:18.480181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da811f152354'
down_revision = '598dfb583552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configvalues', schema=None) as batch_op:
        batch_op.drop_constraint('configvalues_deviceID_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'devices', ['deviceID'], ['id'])

    with op.batch_alter_table('devicefiles', schema=None) as batch_op:
        batch_op.drop_constraint('devicefiles_deviceID_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'devices', ['deviceID'], ['id'])

    with op.batch_alter_table('metadatavalues', schema=None) as batch_op:
        batch_op.drop_constraint('metadatavalues_deviceID_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'devices', ['deviceID'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metadatavalues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('metadatavalues_deviceID_fkey', 'devices', ['deviceID'], ['deviceID'])

    with op.batch_alter_table('devicefiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('devicefiles_deviceID_fkey', 'devices', ['deviceID'], ['deviceID'])

    with op.batch_alter_table('configvalues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('configvalues_deviceID_fkey', 'devices', ['deviceID'], ['deviceID'])

    # ### end Alembic commands ###
