"""Initial migration.

Revision ID: e79e49c54e01
Revises: 59764d25947b
Create Date: 2025-03-05 10:34:47.263563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79e49c54e01'
down_revision = '59764d25947b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firmware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firmware_string', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('firmware_string_hex', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('firmware_string_bootloader', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_column('documentation')
        batch_op.drop_column('documentationLink')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firmware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documentationLink', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('documentation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('firmware_string_bootloader')
        batch_op.drop_column('firmware_string_hex')
        batch_op.drop_column('firmware_string')

    # ### end Alembic commands ###
