"""Initial migration.

Revision ID: e87947fee37e
Revises: d3dc91e55206
Create Date: 2025-04-19 15:47:16.737980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e87947fee37e'
down_revision = 'd3dc91e55206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, create the enum type
    firmware_download_state = postgresql.ENUM('updated', 'pending', 'failed', name='firmware_download_state_enum', create_type=False)
    firmware_download_state.create(op.get_bind())
    
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firmwareDownloadState', sa.Enum('updated', 'pending', 'failed', name='firmware_download_state_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('firmwareDownloadState')
    
    # Drop the enum type after dropping the column
    firmware_download_state = postgresql.ENUM('updated', 'pending', 'failed', name='firmware_download_state_enum', create_type=False)
    firmware_download_state.drop(op.get_bind())

    # ### end Alembic commands ###