"""Initial migration.

Revision ID: fbe27bfd669b
Revises: d267e7a1e881
Create Date: 2024-07-11 10:45:58.816291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe27bfd669b'
down_revision = 'd267e7a1e881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firmware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descrption', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firmware', schema=None) as batch_op:
        batch_op.drop_column('descrption')

    # ### end Alembic commands ###
